### ISSUE TITLE
Make Blueprint a single item

### ISSUE THREAD

**Issue by th3fallen** [Thaccus/Starbase-Nav-Suite#1]
Consider updating the blueprint so all the parts are bolted to a plate or beam or something so users that want to add this to existing ships can print it from the ssc easily and detach the parts to add to their ships.

**Comment by Thaccus** [comment]
After some consideration, I do not intend to do this. This package is definitely intended for use in the SSC. The asteroid avoidance system is a notable example as it is a template and should never be comprised of only four rangefinders. While it would only be a minor inconvenience to me to make this change, it also inconveniences those that intend to use this in its primary mode and hosting two FBEs will just confuse the lowest common denominator further and possibly promote them doing something they shouldn't. Fortunately, the FBE is editable and those that know enough to avoid the spectrum of retrofitting pitfalls also probably know enough to pin things together with cables and a panel so that they can print it out. That being said, I think there is merit to bolting all the buttons to a panel and possibly adding the device hard-points for the receivers so that people have to worry about a little less when using the system in either case.
